# image: Visual Studio 2017
version: '{build}'
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: choco install ant -y -f -i
  - cmd: refreshenv
  - cmd: set GOROOT=
  - cmd: set PATH=%PATH:C:\go\bin;=%
  - cmd: set PATH=%PATH:C:\go\bin=%
  - cmd: set ANT_OPTS=-Xmx512m
  - cmd: set
  - cmd: python --version
  - cmd: java -version
  - cmd: ant -version
# to disable automatic builds by MsBuild
build: off
build_script:
  - ant
  # - bin\buck build buck
# test_script:
  # - bin\buck test --all --test-selectors=:windows_failures.txt --test-selectors=:windows_cxx_support.txt
artifacts:
  # - path: buck-out\gen\programs\buck.pex
  - path: JAVA_Test_CI\Release\buck.pex





# install:
  # - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  # # - choco install gitversion.portable -pre -y
# nuget:
  # account_feed: true
  # project_feed: true
# build:
  # verbosity: minimal
# build_script:
  # - ps: ./AgileCraft.Integration.RTC.Service/build.ps1
# artifacts:
# - path: AgileCraft.Integration.RTC.Service\AgileCraft.Integration.Rtc\bin\Release
  # name: RTCService
  # type: zip
# notifications:
# - provider: Email
  # to:
  # - acey.bunch@agilecraft.com
  # subject: AgileCraft.Integration.Rtc Build Notification
  # on_build_success: true
  # on_build_failure: true
  # on_build_status_changed: false
# - provider: Slack
  # incoming_webhook: https://hooks.slack.com/services/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
  # channel: '#rtc'
  # on_build_success: false
  # on_build_failure: false
  # on_build_status_changed: true
